"use client";
import {toast} from 'sonner';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {decisionValue,parseDecisionCell,renderDecisionCell} from './decision-editing';
import {nextRouteKey} from './route-editing';
import type {DecisionColumn,DecisionTable,DecisionBinding} from './template-api';

function Cell({value,label,editable,save}:{value:string;label:string;editable:boolean;save:(value:string)=>void}){
  return <Input key={value} aria-label={label} className="h-9 min-w-28 text-xs" defaultValue={value} disabled={!editable} onBlur={e=>{if(e.target.value===value)return;try{save(e.target.value);}catch(error){toast.error(String(error));e.target.value=value;}}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>;
}
export function DecisionEditor({table,editable,onChange,onRemove}:{table:DecisionTable;editable:boolean;onChange:(next:DecisionTable)=>void;onRemove:()=>void}){
  const modify=(action:(copy:DecisionTable)=>void)=>{const copy=structuredClone(table);action(copy);onChange(copy);};
  const addColumn=(kind:'inputs'|'outputs')=>modify(copy=>{const id=nextRouteKey(kind==='inputs'?'input':'output',copy[kind].map(c=>c.id));const column:DecisionColumn={id,type:kind==='inputs'?'number':'string',...(kind==='inputs'?{source:'facts',field:id} as const:{})};copy[kind].push(column);for(const row of copy.rules){if(kind==='inputs')row.when[id]=null;else row.then[id]='';}if(kind==='outputs'&&copy.default_output)copy.default_output[id]='';});
  const removeColumn=(kind:'inputs'|'outputs',id:string)=>modify(copy=>{copy[kind]=copy[kind].filter(c=>c.id!==id);for(const r of copy.rules)delete (kind==='inputs'?r.when:r.then)[id];if(kind==='outputs'&&copy.default_output)delete copy.default_output[id];});
  return <section className="space-y-4"><div className="flex gap-2"><Input aria-label="决策表名称" value={table.label} disabled={!editable} onChange={e=>modify(c=>{c.label=e.target.value;})}/><Button variant="ghost" disabled={!editable} onClick={onRemove}>删除表</Button></div>
    <div className="grid grid-cols-2 gap-2"><label className="text-xs">稳定标识<Input aria-label="决策表标识" disabled={!editable} value={table.id} onChange={e=>modify(c=>{c.id=e.target.value;})}/></label><label className="text-xs">版本<Input aria-label="决策表版本" disabled={!editable} value={table.version} onChange={e=>modify(c=>{c.version=e.target.value;})}/></label></div>
    <div className="flex gap-1">{([['UNIQUE','唯一命中'],['FIRST','首条命中'],['COLLECT','收集全部']]as const).map(([policy,label])=><button key={policy} disabled={!editable} className={`rounded-lg border px-3 py-2 text-xs ${table.hit_policy===policy?'border-indigo-400 bg-indigo-50 text-indigo-700':''}`} onClick={()=>modify(c=>{c.hit_policy=policy;})}>{label}</button>)}</div>
    <p className="text-xs leading-5 text-slate-500">每行各条件均满足时命中。* 任意值；&gt;=4 比较；[4..8] 闭区间；A|B 多选。唯一命中会校验规则重叠；首条命中依赖行顺序。</p>
    <div className="overflow-x-auto rounded-xl border"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-2">规则</th>{(['inputs','outputs']as const).flatMap(kind=>table[kind].map(column=><th key={`${kind}:${column.id}`} className={`min-w-36 border-l p-2 text-left ${kind==='outputs'?'bg-emerald-50':''}`}>
      <Cell editable={editable} label={`列名 ${column.id}`} value={column.id} save={id=>modify(copy=>{if(!/^[a-z][a-z0-9_]*$/.test(id)||copy[kind].some(c=>c.id===id))throw new Error('列名需唯一，使用小写英文和下划线');copy[kind].find(c=>c.id===column.id)!.id=id;for(const rule of copy.rules){const cells=kind==='inputs'?rule.when:rule.then;Object.assign(cells,{[id]:cells[column.id]});delete cells[column.id];}if(kind==='outputs'&&copy.default_output){copy.default_output[id]=copy.default_output[column.id];delete copy.default_output[column.id];}})}/>
      <div className="mt-1 flex gap-2"><span className="text-[10px] text-slate-400">{kind==='inputs'?'条件':'输出'}</span><button disabled={!editable} onClick={()=>modify(copy=>{const c=copy[kind].find(c=>c.id===column.id)!;c.type=c.type==='number'?'string':c.type==='string'?'boolean':'number';for(const rule of copy.rules){if(kind==='inputs')rule.when[c.id]=null;else rule.then[c.id]=c.type==='boolean'?false:c.type==='number'?'0':'';}if(kind==='outputs'&&copy.default_output)copy.default_output[c.id]=c.type==='boolean'?false:c.type==='number'?'0':'';delete c.unit;})}>{column.type}</button>{editable&&table[kind].length>1&&<button onClick={()=>removeColumn(kind,column.id)}>×</button>}</div>
      {kind==='inputs'&&<><div className="mt-1 flex gap-1"><button disabled={!editable} className="text-[10px] text-indigo-600" onClick={()=>modify(copy=>{const c=copy.inputs.find(c=>c.id===column.id)!;c.source=c.source==='facts'?'item':'facts';})}>{column.source==='item'?'对象':'场景'}</button><Cell editable={editable} label={`输入字段 ${column.id}`} value={column.field??''} save={field=>modify(copy=>{copy.inputs.find(c=>c.id===column.id)!.field=field;})}/></div>{column.type==='number'&&<Cell editable={editable} label={`输入单位 ${column.id}`} value={column.unit??''} save={unit=>modify(copy=>{copy.inputs.find(c=>c.id===column.id)!.unit=unit||undefined;})}/>}</>}
    </th>))}<th/></tr></thead><tbody>{table.rules.map((rule,index)=><tr key={rule.id} className="border-t"><td className="p-2"><span>{index+1}</span>{editable&&index>0&&<button aria-label={`上移规则 ${rule.id}`} className="ml-2" onClick={()=>modify(c=>{[c.rules[index-1],c.rules[index]]=[c.rules[index],c.rules[index-1]];})}>↑</button>}</td>{table.inputs.map(col=><td key={col.id} className="border-l p-2"><Cell editable={editable} label={`条件 ${rule.id} ${col.id}`} value={renderDecisionCell(rule.when[col.id])} save={raw=>modify(c=>{c.rules[index].when[col.id]=parseDecisionCell(raw,col.type);})}/></td>)}{table.outputs.map(col=><td key={col.id} className="border-l bg-emerald-50/30 p-2"><Cell editable={editable} label={`输出 ${rule.id} ${col.id}`} value={String(rule.then[col.id])} save={raw=>modify(c=>{c.rules[index].then[col.id]=decisionValue(raw,col.type);})}/></td>)}<td className="p-2">{editable&&table.rules.length>1&&<button aria-label={`删除规则 ${rule.id}`} onClick={()=>modify(c=>{c.rules.splice(index,1);})}>×</button>}</td></tr>)}</tbody></table></div>
    {editable&&<div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>modify(c=>{c.rules.push({id:nextRouteKey('rule',c.rules.map(r=>r.id)),when:Object.fromEntries(c.inputs.map(i=>[i.id,null])),then:Object.fromEntries(c.outputs.map(o=>[o.id,o.type==='boolean'?false:o.type==='number'?'0':'']))});})}>＋规则</Button><Button size="sm" variant="outline" onClick={()=>addColumn('inputs')}>＋条件列</Button><Button size="sm" variant="outline" onClick={()=>addColumn('outputs')}>＋输出列</Button></div>}
    <div className="space-y-2"><button disabled={!editable} className="text-xs text-indigo-600" onClick={()=>modify(c=>{if(c.default_output)delete c.default_output;else c.default_output=structuredClone(c.rules[0].then);})}>{table.default_output?'移除默认输出':'设置未命中时的默认输出'}</button>{table.default_output&&table.outputs.map(col=><label key={col.id} className="block text-xs">默认 {col.id}<Cell editable={editable} label={`默认输出 ${col.id}`} value={String(table.default_output![col.id])} save={raw=>modify(c=>{c.default_output![col.id]=decisionValue(raw,col.type);})}/></label>)}</div>
  </section>;
}

export function DecisionBindingEditor({tables,binding,editable,operation,onChange,onOpen}:{tables:DecisionTable[];binding?:DecisionBinding;editable:boolean;operation:boolean;onChange:(binding?:DecisionBinding)=>void;onOpen:()=>void}){
  const table=tables.find(t=>`decision:${t.id}:${t.version}`===binding?.ref);
  const output=table?.outputs.find(c=>c.id===binding?.output);
  return <section className="space-y-2 rounded-xl border border-violet-200 bg-violet-50/40 p-3"><div className="flex justify-between text-xs font-semibold"><span>决策表引用</span><button className="text-violet-600" onClick={onOpen}>管理表 →</button></div>{binding&&editable&&<button className="text-xs text-slate-500" onClick={()=>onChange(undefined)}>移除引用</button>}
    {tables.map(t=><button key={`${t.id}:${t.version}`} disabled={!editable} className={`block w-full rounded border px-2 py-1.5 text-left text-xs ${binding?.ref===`decision:${t.id}:${t.version}`?'border-violet-400 bg-violet-100':''}`} onClick={()=>onChange({ref:`decision:${t.id}:${t.version}`,output:t.outputs[0].id,purpose:'enabled',equals:t.outputs[0].type==='boolean'?true:t.outputs[0].type==='number'?'1':''})}>{t.label} · v{t.version}</button>)}
    {binding&&(!table||!output)&&<p role="alert" className="text-xs text-amber-700">引用的表或输出列已不可用，请重新选择。{binding.ref} / {binding.output}</p>}{!tables.length&&<p className="text-xs text-slate-500">先新建决策表，或使用已发布版本。</p>}{table&&binding&&<><div className="flex flex-wrap gap-1">{table.outputs.map(o=><button key={o.id} disabled={!editable} className={`rounded border px-2 py-1 text-xs ${binding.output===o.id?'border-violet-400':''}`} onClick={()=>onChange({...binding,output:o.id,equals:o.type==='boolean'?true:o.type==='number'?'1':'',purpose:'enabled'})}>{o.id}</button>)}</div>{operation&&<div className="flex gap-1">{(['enabled','operation']as const).map(purpose=><button key={purpose} disabled={!editable} className={`rounded border px-2 py-1 text-xs ${binding.purpose===purpose?'border-violet-400':''}`} onClick={()=>onChange({...binding,purpose})}>{purpose==='enabled'?'控制是否加工':'选择标准工序'}</button>)}</div>}{binding.purpose==='enabled'&&output&&<label className="block text-xs">输出等于以下值时加工<Cell editable={editable} label="决策启用值" value={String(binding.equals??true)} save={value=>onChange({...binding,equals:decisionValue(value,output!.type)})}/></label>}</>}
  </section>;
}
